"""Fix tabel args for address table

Revision ID: d72dd262ca09
Revises: ac0fffade073
Create Date: 2026-01-23 11:49:22.187907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72dd262ca09'
down_revision: Union[str, Sequence[str], None] = 'ac0fffade073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_address_type', 'addresses', ['user_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_address_type', 'addresses', type_='unique')
    # ### end Alembic commands ###
