"""Add unique and check constraint for addresses

Revision ID: f27bb6e9839e
Revises: b5e218e0d362
Create Date: 2026-01-13 11:33:56.791775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27bb6e9839e'
down_revision: Union[str, Sequence[str], None] = 'b5e218e0d362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('type', sa.String(), nullable=False))
    op.drop_column('addresses', 'is_domicile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('is_domicile', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('addresses', 'type')
    # ### end Alembic commands ###
