FROM node:22-slim AS base
WORKDIR /app
EXPOSE 3000

COPY package.json package-lock.json ./
RUN rm -rf node_modules \
    && npm ci


###########
# Stage dev
###########
FROM base AS dev
ENV ENV=development
COPY . .
CMD ["npm", "run", "dev"]

