services:
  identity-service:
    build:
      context: ./backend/services/identity
      target: dev
    image: identity:dev
    volumes:
      - ./backend/services/identity/app:/app
    ports:
      - '8001:8000'
    networks:
      - assicura-app
    depends_on:
      identity-db:
        condition: service_healthy

  identity-db:
    image: postgres:18.2
    container_name: identity-db
    volumes:
      - identity-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=assicura_user
      - POSTGRES_PASSWORD=la0x4Tx0U!d!sb<p
    networks:
      - assicura-app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 20

  ######################################
  driver-license-service:
    build:
      context: ./backend/services/driver-license
      target: dev
    image: driver-license:dev
    volumes:
      - ./backend/services/driver-license/app:/app
    ports:
      - '8002:8001'
    networks:
      - assicura-app
    depends_on:
      driver-license-db:
        condition: service_healthy

  driver-license-db:
    image: postgres:18.2
    container_name: driver-license-db
    volumes:
      - driver-license-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=license
      - POSTGRES_USER=license_user
      - POSTGRES_PASSWORD=52C2V_|zg6Wz
    networks:
      - assicura-app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 20

  ######################################
  vehicle-policy-service:
    build:
      context: ./backend/services/vehicle-policy
      target: dev
    image: vehicle-policy-service:dev
    volumes:
      - ./backend/services/vehicle-policy/app:/app
    ports:
      - '8003:8001'
    networks:
      - assicura-app
    depends_on:
      vehicle-policy-db:
        condition: service_healthy

  vehicle-policy-db:
    image: postgres:18.2
    container_name: vehicle-policy-db
    volumes:
      - vehicle-policy-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=policy
      - POSTGRES_USER=policy_user
      - POSTGRES_PASSWORD=c2w;|=W692<>
    networks:
      - assicura-app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 20

######################################

# web-service:
#   build: 
#     context: ./frontend
#     target: dev
#   image: web-service:dev
#   volumes:
#     - ./frontend:/app
#     - /app/node_modules
#   ports:
#     - '3000:3000'
#   networks:
#     - assicura-app
#   depends_on:
#     - identity-service
#     - driver-license-service

######################################
networks:
  assicura-app:
    name: assicura-app
    driver: bridge

volumes:
  identity-data:
    driver: local
  driver-license-data:
    driver: local
  vehicle-policy-data:
    driver: local
