services:
  identity-service:
    build:
      context: ./backend/identity-service
      target: dev
    image: identity-service:dev
    volumes:
      - ./backend/identity-service/app:/app
    ports:
      - '8001:8001'
    environment:
      - SECRET_KEY=6HM_WkvCsJ6CKJvk2OKvvkR51jU8UAaOZ-Znm4Kbpjkk0xDnI15zD9rM8SYV09KWJcUcI2ONduj5_XWpdbSkBA
      - ALGORITHM=HS256
      - DATABASE_URL=postgresql://admin:admin@identity-db:5432/users
      - SERVICE_NAME=identity-service
      - SERVICE_SECRET=cTi4ZTSL889HBcYehMAg4HTEyCyykCoe6XXPiQGm8k8eSlcWAoTmvvFOQHJWIAIKCnNZzwO5xc2Aw4C_nTX7VQ
    networks:
      - assicura-app
    depends_on:
      - identity-db
    
  driver-license-service:
    build:
      context: ./backend/driver-license-service
      target: dev
    image: driver-license-service:dev
    volumes:
      - ./backend/driver-license-service/app:/app
    ports:
      - '8002:8001'
    environment:
      - SECRET_KEY=6HM_WkvCsJ6CKJvk2OKvvkR51jU8UAaOZ-Znm4Kbpjkk0xDnI15zD9rM8SYV09KWJcUcI2ONduj5_XWpdbSkBA
      - ALGORITHM=HS256
      - DATABASE_URL=postgresql://admin:admin@driver-license-db:5432/driver-license
      - SERVICE_NAME=driver-license-service
      - SERVICE_SECRET=-DZMY0hvzifPyi8Lj_GxBkvuxzxkqY3lf0U5Ckcf-pHpUX61iCjePeSWQTQeUAHtLSqqK9j1gSOc4B0wnlYZUA
    networks:
      - assicura-app
    depends_on:
      - driver-license-db

  web-service:
    build: 
      context: ./frontend
      target: dev
    image: web-service:dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    networks:
      - assicura-app
    depends_on:
      - identity-service
      - driver-license-service

  identity-db:
    image: postgres:18.1-alpine3.23
    container_name: identity-db
    volumes:
      - identity-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - assicura-app
    ports:
      - "5432:5432"

  driver-license-db:
    image: postgres:18.1-alpine3.23
    container_name: driver-license-db
    volumes:
      - driver-license-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=driver-license
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - assicura-app
    ports:
      - "5433:5432"

networks:
  assicura-app:
    name: assicura-app
    driver: bridge

volumes:
  driver-license-data:
    driver: local

  identity-data:
    driver: local
