services:
  identity-service:
    build:
      context: ./backend/services/identity
      target: dev
    image: identity-service:dev
    volumes:
      - ./backend/services/identity/app:/app
    ports:
      - '8001:8001'
    networks:
      - assicura-app
    depends_on:
      identity-db:
        condition: service_healthy



  identity-db:
    image: postgres:18.1-alpine3.23
    container_name: identity-db
    volumes:
      - identity-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - assicura-app

  driver-license-service:
    build:
      context: ./backend/driver-license-service
      target: dev
    image: driver-license-service:dev
    volumes:
      - ./backend/driver-license-service/app:/app
    ports:
      - '8002:8001'
    networks:
      - assicura-app
    depends_on:
      - driver-license-db

  driver-license-db:
    image: postgres:18.1-alpine3.23
    container_name: driver-license-db
    volumes:
      - driver-license-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=driver-license
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - assicura-app
    ports:
      - "5433:5432"

  vehicle-police-service:
    build:
      context: ./backend/vehicle-police-service
      target: dev
    image: vehicle-police-service:dev
    volumes:
      - ./backend/vehicle-police-service/app:/app
    ports:
      - '8003:8001'
    networks:
      - assicura-app
    depends_on:
      - vehicle-police-db

  vehicle-police-db:
    image: postgres:18.1-alpine3.23
    container_name: vehicle-police-db
    volumes:
      - vehicle-police-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vehicle_police
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - assicura-app
    ports:
      - "5434:5432"

  # web-service:
  #   build: 
  #     context: ./frontend
  #     target: dev
  #   image: web-service:dev
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - '3000:3000'
  #   networks:
  #     - assicura-app
  #   depends_on:
  #     - identity-service
  #     - driver-license-service

networks:
  assicura-app:
    name: assicura-app
    driver: bridge

volumes:
  driver-license-data:
    driver: local

  identity-data:
    driver: local

  vehicle-police-data:
    driver: local
