services:
  identity-service:
    build:
      context: ./backend/services/identity
      target: dev
    image: identity:dev
    volumes:
      - ./backend/services/identity/app:/app
    ports:
      - '8001:8001'
    networks:
      - assicura-app
    depends_on:
      identity-db:
        condition: service_healthy



  identity-db:
    image: postgres:18.2
    container_name: identity-db
    volumes:
      - identity-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=assicura_user
      - POSTGRES_PASSWORD=la0x4Tx0U!d!sb<p
    networks:
      - assicura-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

######################################
  driver-license-service:
    build:
      context: ./backend/services/driver-license
      target: dev
    image: driver-license:dev
    volumes:
      - ./backend/services/driver-license/app:/app
    ports:
      - '8002:8001'
    networks:
      - assicura-app
    depends_on:
      driver-license-db:
        condition: service_healthy

  driver-license-db:
    image: postgres:18.2
    container_name: driver-license-db
    volumes:
      - driver-license-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=license
      - POSTGRES_USER=license_user
      - POSTGRES_PASSWORD=52C2V_|zg6Wz
    networks:
      - assicura-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
   
######################################
  vehicle-police-service:
    build:
      context: ./backend/services/vehicle-police
      target: dev
    image: vehicle-police-service:dev
    volumes:
      - ./backend/services/vehicle-police/app:/app
    ports:
      - '8003:8001'
    networks:
      - assicura-app
    depends_on:
      vehicle-police-db:
        condition: service_healthy

  vehicle-police-db:
    image: postgres:18.2
    container_name: vehicle-police-db
    volumes:
      - vehicle-police-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=police
      - POSTGRES_USER=police_user
      - POSTGRES_PASSWORD=c2w;|=W692<>
    networks:
      - assicura-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

######################################

networks:
  assicura-app:
    name: assicura-app
    driver: bridge

volumes:
  identity-data:
    driver: local
  driver-license-data:
    driver: local
  vehicle-police-data:
    driver: local