"""Upgrade field civicNumber in civic_number in addresses table

Revision ID: 766f3653b6b5
Revises: f27bb6e9839e
Create Date: 2026-01-13 12:18:27.720224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766f3653b6b5'
down_revision: Union[str, Sequence[str], None] = 'f27bb6e9839e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('civic_number', sa.String(length=8), nullable=False))
    op.drop_column('addresses', 'civicNumber')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('civicNumber', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.drop_column('addresses', 'civic_number')
    # ### end Alembic commands ###
