"""Create driver license table

Revision ID: ef7d12ef5b40
Revises: 
Create Date: 2026-01-23 12:22:17.570188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7d12ef5b40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_license',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=4), nullable=False),
    sa.Column('number', sa.String(length=11), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('expiry_date > issue_date', name='ck_license_date_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'user_id', name='uq_user_driver_license_type'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_driver_license_user_id'), 'driver_license', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_license_user_id'), table_name='driver_license')
    op.drop_table('driver_license')
    # ### end Alembic commands ###
