"""Add contract policies pivot table

Revision ID: 5768190832ee
Revises: 8b4f23bcd9a7
Create Date: 2026-02-22 19:21:16.444228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5768190832ee'
down_revision: Union[str, Sequence[str], None] = '8b4f23bcd9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_policies',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['insurance_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id', 'policy_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_policies')
    # ### end Alembic commands ###
