"""Add owner_id for contract table

Revision ID: ae056ef625de
Revises: 0ce2e95edfcd
Create Date: 2026-02-25 14:47:38.672839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae056ef625de'
down_revision: Union[str, Sequence[str], None] = '0ce2e95edfcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('owner_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'owner_id')
    # ### end Alembic commands ###
