"""Add insurance policise table

Revision ID: fe09bbba5cb0
Revises: eae4e8c28f81
Create Date: 2026-02-22 18:16:48.360178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe09bbba5cb0'
down_revision: Union[str, Sequence[str], None] = 'eae4e8c28f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.CheckConstraint("vehicle_type IN ('auto','moto','autocarro')", name='ck_insurance_policies_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'vehicle_type', name='uq_vehicle_police_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance_policies')
    # ### end Alembic commands ###
