"""Create addresses table

Revision ID: 43081541074b
Revises: 5f3522be1e0b
Create Date: 2026-01-13 11:24:45.788118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43081541074b'
down_revision: Union[str, Sequence[str], None] = '5f3522be1e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('street', sa.String(length=250), nullable=False),
    sa.Column('civicNumber', sa.String(length=8), nullable=False),
    sa.Column('cap', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=False),
    sa.Column('province', sa.String(length=150), nullable=False),
    sa.Column('is_domicile', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('addresses')
    # ### end Alembic commands ###
