"""Create users table

Revision ID: 5f3522be1e0b
Revises: 
Create Date: 2026-01-13 11:24:09.634462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3522be1e0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('fiscal_id', sa.String(length=16), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('place_of_birth', sa.String(length=150), nullable=False),
    sa.Column('province_of_birth', sa.String(length=150), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('accept_privacy_policy', sa.Boolean(), nullable=False),
    sa.Column('accept_terms', sa.Boolean(), nullable=False),
    sa.Column('subscribe_to_news_letter', sa.Boolean(), nullable=False),
    sa.CheckConstraint("gender IN ('male', 'female')", name='ck_users_gender'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fiscal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
