"""Delete province_of_birth field

Revision ID: ac0fffade073
Revises: 390189255ee4
Create Date: 2026-01-14 21:07:59.617997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0fffade073'
down_revision: Union[str, Sequence[str], None] = '390189255ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'province_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('province_of_birth', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
