"""Add contract table

Revision ID: 8b4f23bcd9a7
Revises: fe09bbba5cb0
Create Date: 2026-02-22 19:10:59.591686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4f23bcd9a7'
down_revision: Union[str, Sequence[str], None] = 'fe09bbba5cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_constraint_for_vehicle', 'contracts', ['vehicle_id'], unique=True, postgresql_where=sa.text("is_active = true"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_constraint_for_vehicle', table_name='contracts', postgresql_where=sa.text("is_active = true"))
    op.drop_table('contracts')
    # ### end Alembic commands ###
