"""Add type in vehicle model

Revision ID: 91241e751d66
Revises: 88e3012139d7
Create Date: 2026-02-22 17:10:20.360244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91241e751d66'
down_revision: Union[str, Sequence[str], None] = '88e3012139d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_table('vehicles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('license_plate', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('vin', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicles_pkey')),
    sa.UniqueConstraint('vin', 'user_id', name=op.f('uq_vehicle_owner'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('vin', name=op.f('vehicles_vin_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=True)
    # ### end Alembic commands ###
