"""Create license category table

Revision ID: 791bd31535dc
Revises: ef7d12ef5b40
Create Date: 2026-01-23 12:22:36.779368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791bd31535dc'
down_revision: Union[str, Sequence[str], None] = 'ef7d12ef5b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license_category',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('min_age', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('min_age >= 14', name='ck_license_min_age'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_foreign_key(None, 'driver_license', 'license_category', ['category'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver_license', type_='foreignkey')
    op.drop_table('license_category')
    # ### end Alembic commands ###
