"""Fix relationship for table driver_license to license_category

Revision ID: e4f7fc6bd7b3
Revises: 791bd31535dc
Create Date: 2026-01-23 13:32:21.321886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f7fc6bd7b3'
down_revision: Union[str, Sequence[str], None] = '791bd31535dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_license', sa.Column('code', sa.String(length=4), nullable=False))
    op.drop_constraint(op.f('uq_user_driver_license_type'), 'driver_license', type_='unique')
    op.create_unique_constraint('uq_user_driver_license_type', 'driver_license', ['code', 'user_id'])
    op.drop_constraint(op.f('driver_license_category_fkey'), 'driver_license', type_='foreignkey')
    op.create_foreign_key(None, 'driver_license', 'license_category', ['code'], ['code'])
    op.drop_column('driver_license', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_license', sa.Column('category', sa.VARCHAR(length=4), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'driver_license', type_='foreignkey')
    op.create_foreign_key(op.f('driver_license_category_fkey'), 'driver_license', 'license_category', ['category'], ['code'])
    op.drop_constraint('uq_user_driver_license_type', 'driver_license', type_='unique')
    op.create_unique_constraint(op.f('uq_user_driver_license_type'), 'driver_license', ['category', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('driver_license', 'code')
    # ### end Alembic commands ###
