FROM python:3.14.2-slim AS base
EXPOSE 5001
WORKDIR /service

RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-client libpq-dev gcc libc6-dev make vim dos2unix && \
    rm -rf /var/lib/apt/lists/*

COPY app /service/app
COPY alembic /service/alembic
COPY alembic.ini /service/alembic.ini
COPY entrypoint.sh /service/entrypoint.sh

# Forza Python a guardare dentro /service
ENV PYTHONPATH=/service
RUN dos2unix entrypoint.sh && chmod +x entrypoint.sh && chmod 755 entrypoint.sh

RUN groupadd -g 1000 fastapi-group && \
    useradd -u 1000 -g fastapi-group -m -s /bin/bash fastapi-user

ENTRYPOINT [ "/service/entrypoint.sh" ]

############
# Stage dev
############
FROM base AS dev
ENV APP_ENV=development


COPY requirements.dev.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.dev.txt

USER fastapi-user

############
# Stage prod
############
FROM base AS prod
ENV APP_ENV=production

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

RUN mkdir -p /var/log/assicurapp \
    && chown -R fastapi-user:fastapi-user /var/log/assicurapp \
    && chmod 755 /var/log/assicurapp

USER fastapi-user

